name: Build RustDesk A-B Windows

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "dual-client-test"
